"""
Django settings for alx_travel_app project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os

# 1️⃣ Define BASE_DIR before using it
BASE_DIR = Path(__file__).resolve().parent.parent

# 2️⃣ Initialize django-environ
env = environ.Env(DEBUG=(bool, True))  # Default DEBUG to True
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))  # Read .env file

# 3️⃣ Default Auto Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 4️⃣ Secret Key
SECRET_KEY = env("SECRET_KEY", default="your-secret-key")

# 5️⃣ Debug Mode
DEBUG = env.bool("DEBUG", default=True)

# 6️⃣ Allowed Hosts
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# 7️⃣ Installed Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'listings',
]

# 8️⃣ Middleware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 9️⃣ CORS Setup
CORS_ALLOW_ALL_ORIGINS = True

# 🔟 URL Configuration
ROOT_URLCONF = 'alx_travel_app.urls'

# 🔹 Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🔹 WSGI Application
WSGI_APPLICATION = 'alx_travel_app.wsgi.application'

# 🔹 Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env("DB_NAME", default="alx_travel_app"),
        'USER': env("DB_USER", default="Banigo"),
        'PASSWORD': env("DB_PASSWORD", default="12345"),
        'HOST': env("DB_HOST", default="localhost"),
        'PORT': env.int("DB_PORT", default=3306),
    }
}

# 🔹 Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🔹 Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# 🔹 Static Files
STATIC_URL = 'static/'

# 🔹 REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}
